{
  "rights": [
    {
      "rightId": 1200004500212221401,
      "cropType": "Far Forward",
      "regionId": 1,
      "commodityId": 1,
      "varietyId": 10,
      "quality": "Band-I",
      "harvestWeek": 15,
      "mbepValue": 1600,
      "farmerRating": 1,
      "villageId": 827,
      "subRegionId": 26,
      "quantity": 1,
      "flexi_1": "",
      "flexi_2": "",
      "flexi_3": "",
      "flexi_4": "",
      "flexi_5": ""
    },
    {
      "rightId": 1200004500212221402,
      "cropType": "Far Forward",
      "regionId": 1,
      "commodityId": 1,
      "varietyId": 10,
      "quality": "Band-I",
      "harvestWeek": 15,
      "mbepValue": 1600,
      "farmerRating": 1,
      "villageId": 827,
      "subRegionId": 26,
      "quantity": 2,
      "flexi_1": "",
      "flexi_2": "",
      "flexi_3": "",
      "flexi_4": "",
      "flexi_5": ""
    },
    {
      "rightId": 1200004500212221403,
      "cropType": "Far Forward",
      "regionId": 1,
      "commodityId": 1,
      "varietyId": 10,
      "quality": "Band-I",
      "harvestWeek": 15,
      "mbepValue": 1600,
      "farmerRating": 1,
      "villageId": 827,
      "subRegionId": 26,
      "quantity": 1,
      "flexi_1": "",
      "flexi_2": "",
      "flexi_3": "",
      "flexi_4": "",
      "flexi_5": ""
    },
    {
      "rightId": 1200004500212221404,
      "cropType": "Far Forward",
      "regionId": 1,
      "commodityId": 1,
      "varietyId": 10,
      "quality": "Band-I",
      "harvestWeek": 15,
      "mbepValue": 1600,
      "farmerRating": 1,
      "villageId": 827,
      "subRegionId": 26,
      "quantity": 1,
      "flexi_1": "",
      "flexi_2": "",
      "flexi_3": "",
      "flexi_4": "",
      "flexi_5": ""
    },
    {
      "rightId": 1200004500212222500,
      "cropType": "Far Forward",
      "regionId": 1,
      "commodityId": 1,
      "varietyId": 10,
      "quality": "Band-I",
      "harvestWeek": 15,
      "mbepValue": 1600,
      "farmerRating": 1,
      "villageId": 193,
      "subRegionId": 16,
      "quantity": 1.5,
      "flexi_1": "",
      "flexi_2": "",
      "flexi_3": "",
      "flexi_4": "",
      "flexi_5": ""
    },
    {
      "rightId": 1200004500212222501,
      "cropType": "Far Forward",
      "regionId": 1,
      "commodityId": 1,
      "varietyId": 10,
      "quality": "Band-I",
      "harvestWeek": 15,
      "mbepValue": 1600,
      "farmerRating": 4,
      "villageId": 193,
      "subRegionId": 16,
      "quantity": 6,
      "flexi_1": "",
      "flexi_2": "",
      "flexi_3": "",
      "flexi_4": "",
      "flexi_5": ""
    },
    {
      "rightId": 1200004500212222502,
      "cropType": "Far Forward",
      "regionId": 1,
      "commodityId": 1,
      "varietyId": 10,
      "quality": "Band-I",
      "harvestWeek": 15,
      "mbepValue": 1600,
      "farmerRating": 4,
      "villageId": 193,
      "subRegionId": 16,
      "quantity": 3.6,
      "flexi_1": "",
      "flexi_2": "",
      "flexi_3": "",
      "flexi_4": "",
      "flexi_5": ""
    }
  ],
  "lot_details": {
    "lot_rights": [
      {
        "rightId": 1200004500212221000,
        "cropType": "Far Forward",
        "regionId": 1,
        "commodityId": 1,
        "varietyId": 10,
        "quality": "Band-I",
        "harvestWeek": 15,
        "mbepValue": 1600,
        "farmerRating": 1,
        "villageId": 827,
        "subRegionId": 26,
        "quantity": 2,
        "flexi_1": "",
        "flexi_2": "",
        "flexi_3": "",
        "flexi_4": "",
        "flexi_5": ""
      },
      {
        "rightId": 1200004500212221001,
        "cropType": "Far Forward",
        "regionId": 1,
        "commodityId": 1,
        "varietyId": 10,
        "quality": "Band-I",
        "harvestWeek": 15,
        "mbepValue": 1600,
        "farmerRating": 1,
        "villageId": 827,
        "subRegionId": 26,
        "quantity": 1.5,
        "flexi_1": "",
        "flexi_2": "",
        "flexi_3": "",
        "flexi_4": "",
        "flexi_5": ""
      },
      {
        "rightId": 1200004500212221002,
        "cropType": "Far Forward",
        "regionId": 1,
        "commodityId": 1,
        "varietyId": 10,
        "quality": "Band-I",
        "harvestWeek": 15,
        "mbepValue": 1600,
        "farmerRating": 1,
        "villageId": 827,
        "subRegionId": 26,
        "quantity": 1,
        "flexi_1": "",
        "flexi_2": "",
        "flexi_3": "",
        "flexi_4": "",
        "flexi_5": ""
      }
    ],
    "lot_upper_threshold": 1,
    "lot_lower_threshold": 1,
    "lot_quantity": 6
  }
}



# request include quantity not equal to required quantity
{
  "rights": [
    {
      "rightId": 1200004500212221401,
      "cropType": "Far Forward",
      "regionId": 1,
      "commodityId": 1,
      "varietyId": 10,
      "quality": "Band-I",
      "harvestWeek": 15,
      "mbepValue": 1600,
      "farmerRating": 1,
      "villageId": 827,
      "subRegionId": 26,
      "quantity": 1,
      "flexi_1": "",
      "flexi_2": "",
      "flexi_3": "",
      "flexi_4": "",
      "flexi_5": ""
    },
    {
      "rightId": 1200004500212221402,
      "cropType": "Far Forward",
      "regionId": 1,
      "commodityId": 1,
      "varietyId": 10,
      "quality": "Band-I",
      "harvestWeek": 15,
      "mbepValue": 1600,
      "farmerRating": 1,
      "villageId": 827,
      "subRegionId": 26,
      "quantity": 2,
      "flexi_1": "",
      "flexi_2": "",
      "flexi_3": "",
      "flexi_4": "",
      "flexi_5": ""
    },
    {
      "rightId": 1200004500212221403,
      "cropType": "Far Forward",
      "regionId": 1,
      "commodityId": 1,
      "varietyId": 10,
      "quality": "Band-I",
      "harvestWeek": 15,
      "mbepValue": 1600,
      "farmerRating": 1,
      "villageId": 827,
      "subRegionId": 26,
      "quantity": 1,
      "flexi_1": "",
      "flexi_2": "",
      "flexi_3": "",
      "flexi_4": "",
      "flexi_5": ""
    },
    {
      "rightId": 1200004500212221404,
      "cropType": "Far Forward",
      "regionId": 1,
      "commodityId": 1,
      "varietyId": 10,
      "quality": "Band-I",
      "harvestWeek": 15,
      "mbepValue": 1600,
      "farmerRating": 1,
      "villageId": 827,
      "subRegionId": 26,
      "quantity": 1,
      "flexi_1": "",
      "flexi_2": "",
      "flexi_3": "",
      "flexi_4": "",
      "flexi_5": ""
    },
    {
      "rightId": 1200004500212222500,
      "cropType": "Far Forward",
      "regionId": 1,
      "commodityId": 1,
      "varietyId": 10,
      "quality": "Band-I",
      "harvestWeek": 15,
      "mbepValue": 1600,
      "farmerRating": 1,
      "villageId": 193,
      "subRegionId": 16,
      "quantity": 0.85,
      "flexi_1": "",
      "flexi_2": "",
      "flexi_3": "",
      "flexi_4": "",
      "flexi_5": ""
    },
    {
      "rightId": 1200004500212222501,
      "cropType": "Far Forward",
      "regionId": 1,
      "commodityId": 1,
      "varietyId": 10,
      "quality": "Band-I",
      "harvestWeek": 15,
      "mbepValue": 1600,
      "farmerRating": 1,
      "villageId": 193,
      "subRegionId": 16,
      "quantity": 0.75,
      "flexi_1": "",
      "flexi_2": "",
      "flexi_3": "",
      "flexi_4": "",
      "flexi_5": ""
    },
    {
      "rightId": 1200004500212222502,
      "cropType": "Far Forward",
      "regionId": 1,
      "commodityId": 1,
      "varietyId": 10,
      "quality": "Band-I",
      "harvestWeek": 15,
      "mbepValue": 1600,
      "farmerRating": 4,
      "villageId": 193,
      "subRegionId": 16,
      "quantity": 3.6,
      "flexi_1": "",
      "flexi_2": "",
      "flexi_3": "",
      "flexi_4": "",
      "flexi_5": ""
    }
  ],
  "lot_details": {
    "lot_rights": [
      {
        "rightId": 1200004500212221000,
        "cropType": "Far Forward",
        "regionId": 1,
        "commodityId": 1,
        "varietyId": 10,
        "quality": "Band-I",
        "harvestWeek": 15,
        "mbepValue": 1600,
        "farmerRating": 1,
        "villageId": 827,
        "subRegionId": 26,
        "quantity": 2,
        "flexi_1": "",
        "flexi_2": "",
        "flexi_3": "",
        "flexi_4": "",
        "flexi_5": ""
      },
      {
        "rightId": 1200004500212221001,
        "cropType": "Far Forward",
        "regionId": 1,
        "commodityId": 1,
        "varietyId": 10,
        "quality": "Band-I",
        "harvestWeek": 15,
        "mbepValue": 1600,
        "farmerRating": 1,
        "villageId": 827,
        "subRegionId": 26,
        "quantity": 1.5,
        "flexi_1": "",
        "flexi_2": "",
        "flexi_3": "",
        "flexi_4": "",
        "flexi_5": ""
      },
      {
        "rightId": 1200004500212221002,
        "cropType": "Far Forward",
        "regionId": 1,
        "commodityId": 1,
        "varietyId": 10,
        "quality": "Band-I",
        "harvestWeek": 15,
        "mbepValue": 1600,
        "farmerRating": 1,
        "villageId": 827,
        "subRegionId": 26,
        "quantity": 1,
        "flexi_1": "",
        "flexi_2": "",
        "flexi_3": "",
        "flexi_4": "",
        "flexi_5": ""
      }
    ],
    "lot_upper_threshold": 0.5,
    "lot_lower_threshold": 0.5,
    "lot_quantity": 6
  }
}